logging.level.root=info
logging.level.com.cwretirement=debug
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{0}.%M - %msg%n
spring.main.banner-mode=off
transaction.file.path=${TRANSACTION_FILE_PATH:classpath:transactions-default.txt}
contribution.reconciliation.url=${CONTRIBUTION_RECONCILIATION_URL:https://postman-echo.com/post}
trade.settlement.reconciliation.url=${TRADE_SETTLEMENT_RECONCILIATION_URL:https://postman-echo.com/post}
